package com.si5a.mykingdom;

import java.util.ArrayList;

public class DataKingdom {

    public static String [] [] data = new String[][] {
            {"Kerajaan Kutai","\"Kerajaan Kutai Mataram atau dikenal dengan Kerajaan Kutai merupakan kerajaan bercorak Hindu di Nusantara. Kerajaan Kutai didirikan oleh Kudungga (seorang kepala adat, ia merubah sistem pertahanan menjadi Kerajaan dan mengangkat dirinya menjadi Raja). Kerajaan ini memiliki bukti sejarah tertua berupa Prasasti Yupa dan berdiri sekitar abad ke-4. \n" +
                    "Pusat kerajaannya terletak di Muara Kaman yang saat ini menjadi sebuah kecamatan di Kabupaten Kutai Kartanegara, Provinsi Kalimantan Timur.Setelah Kudungga wafat, kemudian kerajaan dipimpin oleh sang anak yaitu Asmawarman. Asmawarman dinobatkan menjadi raja dengan cara Hindu dan diberi gelar sebagai Wangsakerta yang artinya 'Pembentuk Keluarga'.\n" +
                    "Kerajan Kutai  didirikan oleh pembesar kerajaan Campa (Kamboja) bernama Kudungga, yang selanjutnya menurunkan Raja Asmawarman, Raja Mulawarman, sampai 27 (dua puluh tujuh) generasi Kerajaan Kutai yaitu :Maharaja Kudungga, gelar anumerta Dewawarman(pendiri). Terdapat 20 nama Raja Kerajaan Kutai : Maharaja Aswawarman (anak Kundungga), Maharaja Mulawarman (anak Aswawarman), Maharaja Marawijaya Warman, Maharaja Gajayana Warman, Maharaja Tungga Warman, Maharaja Jayanaga Warman, Maharaja Nalasinga Warman, Maharaja Nala Parana Tungga, Maharaja Gadingga Warman Dewa, Maharaja Indra Warman Dewa, Maharaja Sangga Warman Dewa, Maharaja Candrawarman, Maharaja Sri Langka Dewa, Maharaja Guna Parana Dewa, Maharaja Wijaya Warman, Maharaja Sri Aji Dewa, Maharaja Mulia Putera, Maharaja Nala Pandita, Maharaja Indra Paruta Dewa, Maharaja Dharma Setia\n" +
                    "Juga terdapat tujuh prasasti Yupa yang ditemukan semua peninggalan itu ditulis dalam bahasa Pallawa dan Sansekerta.Peninggalan Kerajaan Kutai yang paling penting berupa tujuh buah Prasasti Yupa yang dibuat sekitar tahun 350-400 masehi. Ketopong Sultan : Yaitu mahkota Sultan Kerajaan Kutai yang terbuat dari emas dengan bobot 1,98 kg serta dilengkapi dengan permata, , Kura-kura Emas : Kura-kura emas yang sekarang tersimpan di Museum Mulawarman ini ditemukan di daerah Long Lalang yang masih kawasan hulu sungai Mahakam,  dan merupakan persembahan dari pangeran di sebuah kerajaan Cina untuk putri Raja Kutai, yaitu Aji Bidah Putih, Gamelan Gajah Prawoto : Peninggalan Kerajaan Kutai berupa Gamelan Gajah Prawoto ini dipercaya berasal dari Jawa, Pedang Sultan Kutai : Pedang itu disimpan pada Museum Nasional Jakarta. Terbuat dari bahan emas yang padat. Di bagian gagang pedang terdapat ukiran seekor harimau yang sedang bersiap menerkam musuh. Sedangkan ujung sarung pedang dihiasi ukiran seekor buaya, Kalung Ciwa :Benda yang berbentuk perhiasan ini dipercaya dibuat pada masa kepemimpinan Sultan Aji Muhammad, kalung ciwa ditemukan pada tahun 1890 oleh warga sekitar di Danau Lapan, Muara Kaman."}

            {"Kerajaan Sribangun","\"Kerajaan Sribangun, Sejarah Kota Bangun (Sri Bangun) Sebuah Kerajaan Dengan Corak Buddha. Diperkirakan merupakan negeri bawahan dari kerajaan Kutai Martadipura (abad ke4 – 1635).Kota Bangun terletak sekitar 88 Km dari Tenggarong Ibu Kota Kabupaten Kutai Kartanegara, terletak di sisi kiri mudik Sungai Mahakam. Merupakan sebuah daerah yang memiliki sejarah peradaban lama. Bekas wilayah Kerajaan Sri Bangun dengan Rajanya yang paling terkenal bernama Qeva.\n" +
                    "Sri Bangun diperkirakan merupakan negeri bawahan dari Kerajaan Martadipura, namun berbeda dengan Martadipura yang Hindu, Kerajaan ini malah menunjukkan corak sebagai Kerajaan Budha dengan ditemukannya beberapa peninggalan seperti Arca Buddha Pengembara dari Perunggu, dan Patung Lembu Nandi yang oleh masyarakat setempat disebut sebagai Singa Noleh.\n" +
                    "Situs Sri Bangun ini hingga sekarang tetap di keramatkan penduduk Kutai Kartanegara, karena dipercaya Kerajaan Sri Bangun yang memang misterius tersebut, hingga kini masih ada secara gaib.\n" +
                    "Banyak warga yang telah melihat bayangan Istana megah di wilayah pada waktu-waktu tertentu, terkadang pula ditemukan beberapa lelaki dan wanita misterius yang apabila diikuti menghilang begitu saja.\n"}

            {"Kerajaan Wijayapura","Pada abad ke-7 di bagian utara Kalimantan Barat terdapat kerajaan yang bercorak Hindu-Budha, yaitu kerajaan Wijayapura yang dilanjutkan Kerajaan Nek Riuh (13 M – 14 M), Kerajaan Tan Unggal (15 M), dan Panembahan Sambas pada abad 16 M. Keempat kerajaan tersebut murni bercorak Hindu-Budha, tapi masuknya agama Islam di Kalimantan Barat, Panembahan Sambas merupakan kerajaan terakhir di utara Kalimantan Barat.Kerajaan Sambas sebenarnya merupakan koloni dari Kerajaan Bakulapura, kemudian menjadi koloni dari Kerajaan Tanjungpura, yaitu Kerajaan bawahan Majapahit di Pulau Kalimantan. Di dalam Pupuh XIII dan XIV dari kitab Negarakertagama disebutkan bahwa Kerajaan Majapahit menguasai hampir seluruh Nusantara tak terkecuali kerajaan-kerajaan di Pulau Kalimantan.Kerajaan Sambas sebenarnya merupakan koloni dari Kerajaan Bakulapura, kemudian menjadi koloni dari Kerajaan Tanjungpura, yaitu Kerajaan bawahan Majapahit di Pulau Kalimantan. Di dalam Pupuh XIII dan XIV dari kitab Negarakertagama disebutkan bahwa Kerajaan Majapahit menguasai hampir seluruh Nusantara tak terkecuali kerajaan-kerajaan di Pulau Kalimantan. Raja pertama Kerajaan Panembahan Sambas adalah ayah dari Ratu Timbang Paseban yang tidak diketahui namanya. Setelah sang raja mangkat, Ratu Timbang Paseban kemudian diangkat sebagai pewaris tahta. Dari Ratu Timbang Paseban kemudian tahta turun kepada Ratu Sapudak adiknya. Sebutan ratu adalah kebiasaan penyebutan di Jawa yang memiliki arti sama dengan raja pria. Jadi ratu yang dimaksudkan bukan raja bergender wanita. Peninggalan Kerajaan Wijayapura ialah ; Arca Budha emas di Sambas, Arca Budha perak di Sambas, Arca Budha perunggu di Sambas"}

            {"Kerajaan Kahuripan","Diduga nama Kerajaan Kuripan sebutan lain dari Kerajaan Tabalong yang disebutkan dalam Kakawin Nagarakretagama yang ditulis pujangga Majapahit yakni Mpu Prapanca pada tahun 1365. Sebutan Kerajaan Tabalong berdasarkan nama kawasan di mana kerajaan tersebut berada. Sedangkan nama Kuripan mungkin nama ibu kotanya saat itu. Nama Kuripan diduga adalah nama lama Amuntai (kota) di Kabupaten Hulu Sungai Utara yang terletak di sekitar muara sungai Tabalong.\n" +
                    "Menurut Tutur Candi, Kerajaan Kahuripan adalah kerajaan yang lebih dulu berdiri sebelum Kerajaan Negara Dipa. Karena raja Kerajaan Kahuripan menyayangi Empu Jatmika sebagai anaknya sendiri maka setelah dia tua dan mangkat kemudian seluruh wilayah kerajaannya (Kahuripan) dinamakan sebagai Kerajaan Negara Dipa, yaitu nama daerah yang didiami oleh Empu Jatmika. (Fudiat Suryadikara, Geografi Dialek Bahasa Banjar Hulu, Depdikbud, 1984\n" +
                    "Kerajaan Kuripan ini diduga adalah kerajaan yang sama dengan Kerajaan Tanjungpuri atau Kerajaan Nan Sarunai atau mungkin pula Nan Sarunai adalah bawahan dari Kuripan. Selanjutnya kekuasaan kerajaan orang pribumi kemudian digantikan penguasa baru daerah ini yaitu Dinasti Negara Dipa yang berdarah Majapahit.\n" +
                    "Peninggalan Kerajaan Kuripan : Candi Belahan atau dikenal juga dengan sebutan Petirtaan Belahan atau Sumber Tetek, merupakan petirtaan bersejarah yang berada di sisi timur Gunung Penanggungan.Lokasi candi ini di Dusun Belahanjowo, Desa Wonosunyo, Kecamatan Gempol, Kabupaten Pasuruan.Cagar budaya candi Jalatunda ini tepatnya terletak di bagian utara lereng gunung Penanggungan, desa Seloliman, Kecamatan Trawas, Kabupaten Mojokerto Jawa Timur, Prasasti Kamalagyan terletak di Dusun Klagen, Desa Tropodo, Kecamatan Krian Kabupaten Sidoarjo, Prasasti ini terbuat dari bahan lempeng batu andesit besar yang ditegakkan, dengan ukuran lebar 115 cm, tebal 28 cm dan tinggi 215 cm. Selain prasasti utama dengan ukuran besar, terdapat juga batu kecil di sampingnya, Prasasti Pucangan merupakan peninggalan Raja Airlangga yang dibuat pada tahun 1042 M atau 963 Saka. Nama Pucangan diambil dari isi prasasti yang menceritakan adanya perintah membangun pertapaan di Pucangan, sekitar Gunung Penanggungan, Kabupaten Mojokerto, Jawa Timur, Prasasti Pucangan ditulis dengan dua bahasa, yakni bahasa Sanskerta dan Jawa Kuno. Pucangan dibuat untuk menjelaskan tentang peristiwa dan silsilah keluarga kerajaan secara runtut dan berurutan."}

            {"Kerajaan Negara Dipa","Kerajaan Negara Dipa merupakan sebuah kerajaan yang pernah berdiri di wilayah Provinsi Kalimantan Selatan pada sekitar tahun 1380. Sebelum berdiri, Negara Dipa merupakan sebuah wilayah di bawah kekuasaan Kerajaan Kuripan. Kerajaan Negara Dipa didirikan oleh Ampu Jatmika yang merupakan anak kesayangan dari raja terakhir Kerajaan Kuripan. Lambung Mangkurat merupakan raja yang populer saat memerintah Kerajaan Negara Dipa.Sebelum berdiri, Kerajaan Negara Dipa berada di bawah kekuasaan Kerajaan Kuripan yang terletak di kecamatan Danau Panggang, Hulu Sungai Utara, Kalimantan Selatan. Saat itu, Raja Kerajaan Kuripan sangat sayang kepada Ampu Jatmika dan menganggapnya seperti anaknya sendiri. Ampu Jatmika merupakan seorang saudagar asal Keling, Kediri, yang dikirim Raja Majapahit, Hayam Wuruk, ke Kalimantan pada 1355. Ia ditugaskan untuk menyerang Kerajaan Dayak Ma'anyan Nan Sarunai. Setelah berhasil mengalahkan Kerajaan Dayak Ma'anyan Nan Sarunai, Ampu Jatmika kemudian mendirikan Kerajaan Negara Dipa pada 1380. Saat itu, Kerajaan Negara Dipa berada di bawah kekuasaan Kerajaan Kuripan yang sudah eksis terlebih dahulu. Setelah sang raja Kerajaan Kuripan meninggal dunia, takhta dilimpahkan kepada Ampu Jatmika. Ampu Jatmika kemudian mengganti nama Kerajaan Kuripan menjadi Negara Dipa pada 1380. Saat itu, ibu kota Kerajaan Negara Dipa berada di Candi Agung yang terletak di sekitar hulu sungai Bahan.Setelah Ampu Jatmika turun takhta, Negara Dipa kemudian dipimpin oleh Lambung Mangkurat dari 1380 hingga 1387. Saat itu, Negara Dipa berhasil memperluas wilayah yang terbentang dari Tanjung Silat sampai Tanjung Puting. Selain itu, Kerajaan Negara Dipa juga memiliki daerah-daerah bawahan yang disebut wilayah Sakai. Wilayah Sakai ini masing-masing dipimpin oleh seorang Mantri Sakai. Adapun wilayah Sakai yang ditaklukan oleh Lambung Mangkurat tercatat dalam Hikayat Banjar. Lambung Mangkurat memiliki seorang putri bernama Junjung Buih yang dipersiapkan untuk meneruskan kepemimpinan Kerajaan Negara Dipa. Junjung Buih kemudian menikah dengan seorang bangsawan Majapahit yang kemudian secara bersama-sama memerintah Negara Dipa. Setelah menikah, suami Junjung Buih bergelar Maharaja Surya Nata. Kerajaan Negara Dipa berakhir dengan berubah nama menjadi Kerajaan Daha.\n" +
                    "Raja yang pernah memimpin kerajaan Negara DIPA : Ampu Jatmika Lambung Mangkurat Raden Galuh Ciptasari Raden Aria Gegombak Aria Dewangsa Raden Sekar Sungsang\n" +
                    "\n"}

            {"Kerajaan Negara Daha","Sejarah Kerajaan Daha atau Negara Daha merupakan kerajaan bercorak Hindu yang pernah ada di Nusantara, tepatnya di Kalsel. Kerajaan Daha merupakan pendahulu dari kesultanan Banjar dan merupakan kelanjutan dari Kerajaan Negara Dipa. Pusat kerajaan berada di Muara Huluk, sedangkan pusat perdagangan atau perekonomian Kerajaan Daha berada di Muara Rampiau. Pada perkembangan selanjutnya, pusat perekonomian akhirnya dipindahkan di Bandar Muara Bahan.\n" +
                    "Perkembangan selanjutnya mengenai Kerajaan Daha kemudian menjadi sebuah kerajaan Islam pada masa kesultanan Banjar. Kerajaan Daha berkembang pesat dan berhasil mempunyai bandar dagang dan pelabuhan. Pelabuhan dan bandar dagang tersebut letaknya di Muara Bahan dan berjarak 165 km di sebelah utara Kota Banjarmasin, ibukota provinsi Kalimantan Selatan. Asal usul Kerajaan Daha sebenarnya adalah kelanjutan dari kekuasaan Kerajaan Dipa yang dahulunya berkuasa di wilayah Kuripan (Kota Amuntai). Pusat pemerintahan Kerajaan Dipa terpaksa harus dilakukan karena bertujuan untuk menghindar dari bencana. Bencana ini terjadi karena anggapan kota ini sudah tidak atau hilang tuahnya. Pemindahan pusat pemerintahan Kerajaan Daha kemudian dilakukan, kemudian berpindah di hilir sungai Negara. Pemindahan ini mengakibatkan nama kerajaan berganti setelah 3 kali pergantian ibukotanya, kerajaan ini pun berganti nama menjadi Kerajaan Daha atau Kerajaan Negara Daha.\n" +
                    "Wilayah Kekuasaan Kerajaan Daha, yaitu meliputi wilayah negara, wilayah ini sering disebut sebagai daerah inti atau sebagai pusat pemerintahan dan juga pusat ibu kota kerajaan. Wilayah kekuasaan Kerajaan Daha merupakan bekas wilayah sebelumnya merupakan menjadi daerah kekuasaan Dipa dan juga taklukannya. Wilayah taklukan meliputi Batang Pitap, Batang Lawai, Batang Emas, Batang Alai, Sukadana, Sambas, Batang Amandit, Tabalong, Kotawaringin, Pasir, Kutai, Krasikan dan Berau.\n" +
                    "Raja yang pernah memimpin Kerajaan Negara Daha : Maha raja Sari Kaburangan dari tahun 1448 sampai 14486, Maha raja Sukarama dari tahun 1486 sampai 1525, Maha raja Pangeran Aria Mangkubumi, Maha raja Pangeran Tumenggung dari 1525 sampai 1526.\n" +
                    "Peninggalan Kerajaan Negara Daha : Kerajaan Daha memiliki peninggalan sejarah berupa benda pusaka dan barang-barang yang merupakan bekas peninggalan Kerajaan Majapahit. Peninggalan tersebut terdiri dari ; gamelan bernama larasati, mahkota raja, gong, canang dengan nama Macan Patuk, tombak dengan nama putos, serta keris dengan nama masa girang dan jokopitoron, keris baru lembah, payung kerajaan, dan singgasana  emas, naga salira berbalut dari emas dan gagangnya dari berlian, prisai terbuat dari emas, prisai terbuat dari perak, 5 tombak, dan sebilah pedang.Selain peninggalan tersebut, Kerajaan Daha juga meninggalkan beberapa peninggalan berupa peninggalan arkeologis, yaitu penemuan candi yang diberi nama candi laras, letaknya di Kec. Candi Laras Selatan, Desa Margasai.\n" +}

            {"Kerajaan Tarumanegara","Kerajaan Tarumanegara berdiri pada abad ke-4, atau lebih tepatnya pada 358 M. Pendiri Kerajaan Tarumanegara bukan berasal dari nusantara namun Maharesi Jayasingawarman yang berasal dari India. Raja Jayasingawarman memberi nama kerajaannya Tarumanegara dari nama pohon tarum yang banyak tumbuh di daerah tersebut. Jayasingawarman memerintah dari tahun 358 M sampai 328 M, dan setelahnya memutuskan untuk menjadi petapa. Kepemimpinan Kerajaan Tarumanegara lalu dilanjutkan oleh Raja Dharmayawarman. Tak banyak sumber sejarah yang menyebut masa kepemimpinan Raja Dharmayawarman (382-395 M). Catatan sejarah justru banyak menyebut kepemimpinan raja ketiga yaitu Purnawarman sebagai raja yang berhasil membawa Kerajaan Tarumanegara mencapai kejayaan. Pada masa kepemimpinannya di tahun 397 masehi, Purnawarman membangun ibu kota kerajaan bernama Sundapura di kawasan pantai yang jadi asal-usul \"Sunda\" sekarang. Selain itu seperti yang disebut dalam Prasasti Tugu, raja juga memerintahkan penggalian Sungai Gomati sepanjang 12 km yang berfungsi sebagai jalur perdagangan, mengendalikan banjir, dan menghindari kekeringan yang pada musim kemarau. Di bawah kekuasaannya Kekuasaan Tarumanegara meliputi hampir seluruh wilayah Jawa Barat, mulai dari Banten, Jakarta, Bogor, dan Cirebon. Tak hanya di dalam negeri, Kerajaan Tarumanegara bahkan menjalin hubungan diplomatik dengan Cina. Salah satu bukti kejayaan Raja Purnawarman adalah dilakukannya persembahan 1.000 ekor sapi kepada para Brahmana yang juga tercantum pada Prasasti Tugu. \n" +
                    "Raja yang pernah memimpin kerajaan Tarumanegara : Jayasingawarman (358-382 M) Dharmayawarman (382-395 M) Purnawarman (395-434 M) Wisnuwarman (434-455 M) Indrawarman (455-515 M) Candrawarman (515-535 M) Suryawarman (535-561 M) Kertawarman (561-628 M) Sudhawarman (628-639 M) Hariwangsawarman (639-640 M) Nagajayawarman (640-666 M) Linggawarman (666-669 M). \n" +
                    "Prasasti Peninggalan kerajaan Tarumanegara : Prasasti Ciareteun, ditemukan di Ciampea, Bogor. Prasasti Pasir Koleangkak, ditemukan di sebelah barat kota Bogor. Prasasti Kebon Kopi, ditemukan di kampung Muara Hilir, Cibungbulang. Prasasti Tugu, ditemukan di daerah Tugu, Jakarta. Prasasti Pasir Awi, ditemukan di daerah Pasir Awi, Bogor. Prasasti Muara Cianten, ditemukan di daerah Bogor. Prasasti Cidanghiang atau Lebak.\n" +
                    "\n"}

            {"Kerajaan Sunda Galuh",""}

            {"Kerajaan Kalingga",""}

            {"Kerajaan Kediri",""}

            {"Kerajaan Singasari",""}

            {"Kerajaan Majapahit",""}

            {"Kerajaan Melayu Dharmasraya"," "}

            {"Kerajaan Sriwijaya","Kerajaan Sriwijaya diketahui berdiri pada abad ke- 7 dan pendirinya disebut Dapunta Hyang Sri Jayanasa.  Pada masa kejayaannya, Sriwijaya mengontrol perdagangan jalur utama. Selat Malaka dan daerah kekuasaannya meliputi Kamboja, Thailand Selatan, Semenanjung Malaya, Sumatra, dan sebagian Jawa. Dalam prasasti Kedukan Bukit tercatat bahwa tahun 682 masehi menjadi tahun di mana kerajaan ini resmi didirikan. Nama Sriwijaya diambil dari Bahasa Sansekerta dari kata ‘sri’ yang berarti cahaya dan ‘wijaya’ yang artinya kemenangan. Sebagai negara maritim, berdirinya Kerajaan Sriwijaya kemudian memberikan pengaruh besar di nusantara. Puncak Kejayaan Kerajaan Sriwijaya Dua abad setelah didirikan tepatnya pada abad ke-9, di bawah kepemimpinan Raja Balaputradewa (856 M) Kerajaan Sriwijaya mencapai masa keemasan. Balaputradewa merupakan anak dari Samaratungga, Raja Mataram Kuno, yang masih keturunan Dinasti Syailendra. Ayahnya dikenal sebagai pendiri Candi Borobudur, yang kini menjadi Candi Buddha terbesar di Dunia. Pengaruh Kerajaan Sriwijaya di bawah kepemimpinan Balaputradewa meluas dari menguasai perdagangan di jalur utama Selat Malaka hingga ke Kamboja, Thailand Selatan, Semenanjung Malaya, Sumatera, dan sebagian Pulau Jawa. Dari segi penyebaran agama, Kerajaan Sriwijaya juga menjadi pusat agama Buddha Mahayana di Asia Tenggara. Raja-raja yang Pernah Memimpin di Sriwijaya Inilah daftar raja-raja yang pernah memimpin Kerajaan Sriwijaya :Dapunta Hyang Sri Jayanasa (683 M), Indrawarman (702 M), Rudra Wikrama (728-742 M), Sanggramadhananjaya (775 M), Dharanindra/Rakai Panangkaran (778 M), Samaragrawira/Rakai Warak (782 M), Dharmasetu (790 M), Samaratungga/Rakai Garung (792 M), Balaputradewa (856 M), Sri Udayadityawarman (960 M), Sri Wuja atau Sri Udayaditya (961 M), Hsiae-she (980 M), Sri Cudamani Warmadewa (988 M), Malayagiri/Suwarnadwipa (990 M), Sri Marawijayottunggawarman (1008 M), Sumatrabhumi (1017 M), Sri Sanggrama Wijayatunggawarman (1025 M), Sri Dewa (1028 M), Dharmawira(1064 M), Sri Maharaja (1156 M), Trailokyaraja Maulibhusana Warmadewa (1178 M).\n" +
                    "Prasasti peninggalan Kerajaan Sriwijaya : Prasasti Talang Tuo ditemukan di di Desa Gadus daerah Talang Tuwo, sebelah barat Kota Palembang. Prasasti Talang Tuo memiliki angka tahun 606 C atau 684 Masehi. Prasasti ini ditulis dengan huruf pallawa dengan bahasa melayu kuno yang berisi tentang pembuatan taman Sri-ksetra oleh punta hyang Sri Jayanaga untuk kemakmuran semua makhluk. Doa dan harapan yang terdapat di dalam prasasti ini menunjukkan sifat-sifat dari agama Buddha,Prasasti Telaga Batu berbentuk batu lempeng dan tidak berangka tahun. Isi Prasasti Telaga Batu adalah kutukan yang menakutkan bagi siapapun yang tidak taat terhadap perintah-perintah raja,Prasasti Karang Brahi ditemukan di daerah Jambi. Prasasti Karang Brahi memiliki angka tahun 608 C atau 686 Masehi. Prasasti ini ditulis dengan huruf pallawa dengan bahasa melayu kuno. Isinya Prasasti Karang Brahi adalah permintaan kepada para dewa agar menjaga Sriwijaya, menghukum setiap orang yang bermaksud jahat dan mendurhakai kekuasaan sriwijaya serta menjamin keselamatan mereka yang taat dan setia,Prasasti Ligor ditemukan di Tanah Genting Kra di daerah Ligor. Prasasti Ligor memiliki angka tahun 697 C atau 775 Masehi. Prasasti ini memiliki tulisan di kedua sisinya dengan huruf pallawa dengan bahasa melayu kuno. Isi dari Prasasti Ligor di bagian belakang yaitu: dikeluarkan oleh raja Sriwijaya, disebut seorang raja bernama Wisnu dari keluarga Sailendra. Raja ini dipuja dengan nama Raja Sanggramadhananjaya seperti yang dijumpai dalam Prasasti Kelurak, Prasasti Kedukan Bukit ditemukan di tepi Sungai Tatang, dekat wilayah Palembang.\n"}

    }
}
